import 'package:hive/hive.dart';

part 'cart_item.g.dart'; // This part file is generated by Hive

@HiveType(typeId: 0) // Use a unique typeId for each HiveType in your app
class CartItem extends HiveObject {
  @HiveField(0)
  late String title;

  @HiveField(1)
  late double price;

  @HiveField(2)
  late String image;

  CartItem({
    required this.title,
    required this.price,
    required this.image,
  });
}
//import '../widgets/custom_button.dart';
// import '../widgets/custom_input.dart';